Vagrant.configure("2") do |config|
  ["node1", "node2", "node3"].each do |node|
    config.vm.define node do |srv|
      srv.vm.box = "centos/7"
      srv.vm.hostname = node

      if Vagrant.has_plugin?("vagrant-libvirt")
        srv.vm.provider :libvirt do |libvirt|
          libvirt.memory = 3072
        end
      else
        srv.vm.provider :virtualbox do |vbox|
          vbox.memory = 3072
        end
      end

      srv.vm.provision "chef_solo" do |chef|
        chef.arguments = "--chef-license accept"
        chef.cookbooks_path = "../cookbooks"
        chef.add_recipe "base"
        chef.add_recipe "dnsmasq"
        chef.add_recipe "docker"
        chef.add_recipe "consul"
        chef.add_recipe "vault"
        chef.add_recipe "nomad::nginx"
      end
    end
  end
end
