Vagrant.configure("2") do |config|
  config.vm.define :node1 do |node1|
    node1.vm.box = "centos/7"
    node1.vm.hostname = "node1"

    if Vagrant.has_plugin?("vagrant-libvirt")
      node1.vm.provider :libvirt do |libvirt|
        libvirt.memory = 2048
      end
    else
      node1.vm.provider :virtualbox do |vbox|
        vbox.memory = 2048
      end
    end

    node1.vm.provision "shell", path: "../scripts/prep.sh"
    node1.vm.provision "shell", path: "../scripts/nomad.sh"
    node1.vm.provision "shell", path: "../scripts/docker.sh"
  end
end
