{
 "title": "BlackBox Simple",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Prometheus",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://prometheus:9090\"}  "
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://grafana:3000\"}  "
    }
   ]
  },
  {
   "title": "Cortex",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "probe_success{instance=\"http://cortex:9009\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}