global:
  scrape_interval:     15s
  evaluation_interval: 15s

remote_write:
  - url: http://cortex:9009/api/prom/push
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra_exporter:8080']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://prometheus:9090
          - http://cortex:9009
          - http://grafana:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
